'use client';
import {useMemo,useState} from 'react';import {useRouter} from 'next/navigation';import {BASE_PRICE_CENTS,euro,projectPriceCents,Size} from '@/lib/pricing';import {addCartProject} from '@/lib/cart';
const occasions=['Рожден ден','Годишнина','Пенсиониране','Супергерой','Двойка','Семейство','Учител','Колега','Футболист','Професия','Пътуване','Друго'];
export default function Configurator(){const router=useRouter();const[step,setStep]=useState(1);const[occasion,setOccasion]=useState('Рожден ден');const[size,setSize]=useState<Size>('A4');const[people,setPeople]=useState(1);const[description,setDescription]=useState('');const[inscription,setInscription]=useState('');const[files,setFiles]=useState<File[]>([]);const price=useMemo(()=>projectPriceCents(size,people),[size,people]);
const next=()=>setStep(s=>Math.min(7,s+1));const back=()=>setStep(s=>Math.max(1,s-1));const addToCart=()=>{addCartProject({occasion,size,people,description,inscription,fileNames:files.map(file=>file.name)});router.push('/kolichka')};return <div className="config-shell"><section className="panel"><div className="progress">{[1,2,3,4,5,6,7].map(n=><span className={n<=step?'done':''} key={n}/>)}</div><p className="kicker">Стъпка {step} от 7</p>
{step===1&&<><h2>За какъв повод е карикатурата?</h2><div className="option-grid">{occasions.map(x=><button className={`option ${occasion===x?'active':''}`} onClick={()=>setOccasion(x)} key={x}>{x}</button>)}</div></>}
{step===2&&<><h2>Изберете размер</h2><div className="option-grid">{(Object.keys(BASE_PRICE_CENTS) as Size[]).map(x=><button className={`option ${size===x?'active':''}`} onClick={()=>setSize(x)} key={x}><b>{x}</b><br/><small>от {euro(BASE_PRICE_CENTS[x])}</small></button>)}</div><div className="notice">A4 — 30×20 см · A3 — 40×30 см · A2 — 70×50 см</div></>}
{step===3&&<><h2>Колко лица да нарисуваме?</h2><div className="option-grid">{[1,2,3,4,5,6].map(x=><button className={`option ${people===x?'active':''}`} onClick={()=>setPeople(x)} key={x}>{x} {x===1?'лице':'лица'}<br/><small>{euro(projectPriceCents(size,x))}</small></button>)}</div><p className="notice">Цената включва едно лице. Всяко следващо лице е +10 €.</p></>}
{step===4&&<><h2>Качете снимките</h2><div className="field"><label htmlFor="photos">JPG, JPEG, PNG или WEBP · до 10 MB на файл · максимум 12</label><input id="photos" type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={e=>setFiles(Array.from(e.target.files||[]).slice(0,12))}/></div><p className="notice">Добавете ясни снимки, на които лицето се вижда добре. Можете да качите различни снимки за прическата, облеклото и позата.</p>{files.map((f,i)=><p key={f.name}>{i+1}. {f.name} — лице {(i%people)+1}</p>)}</>}
{step===5&&<><h2>Опишете идеята си</h2><div className="field"><label htmlFor="idea">Фон, облекло, поза и забавна ситуация</label><textarea id="idea" rows={8} maxLength={2000} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Опишете фона, облеклото, позата, хобитата, професията, предметите и забавната ситуация, които искате да бъдат включени."/><small>{description.length}/2000</small></div></>}
{step===6&&<><h2>Желаете ли надпис?</h2><div className="form-grid"><div className="field full"><label htmlFor="inscription">Текст на надписа</label><input id="inscription" maxLength={120} value={inscription} onChange={e=>setInscription(e.target.value)} placeholder="Напр. Честит юбилей, Иван!"/></div><div className="field"><label>Предпочитано разположение</label><select><option>По преценка на художника</option><option>Горе</option><option>Долу</option></select></div><div className="field"><label>Допълнителна бележка</label><input maxLength={300}/></div></div></>}
{step===7&&<><h2>Преглед на проекта</h2><div className="summary-row"><span>Повод</span><b>{occasion}</b></div><div className="summary-row"><span>Размер / лица</span><b>{size} / {people}</b></div><div className="summary-row"><span>Снимки</span><b>{files.length}</b></div><div className="summary-row"><span>Описание</span><b>{description?description.slice(0,70)+'…':'—'}</b></div><div className="summary-row"><span>Базова цена</span><b>{euro(BASE_PRICE_CENTS[size])}</b></div><div className="summary-row"><span>Допълнителни лица</span><b>{euro((people-1)*1000)}</b></div><button className="button" type="button" onClick={addToCart} style={{marginTop:24,width:'100%'}}>Добави в количката</button></>}
<div className="actions">{step>1&&<button className="button ghost" onClick={back}>← Назад</button>}{step<7&&<button className="button" onClick={next}>Продължи →</button>}</div></section><aside className="summary"><p>Вашата карикатура</p><h3>{occasion}</h3><div className="summary-row"><span>Размер</span><b>{size}</b></div><div className="summary-row"><span>Брой лица</span><b>{people}</b></div><div className="summary-row"><span>Базова цена</span><b>{euro(BASE_PRICE_CENTS[size])}</b></div>{people>1&&<div className="summary-row"><span>Доп. лица</span><b>{euro((people-1)*1000)}</b></div>}<strong>{euro(price)}</strong><small>Крайната цена се преизчислява и потвърждава защитено на сървъра.</small></aside></div>}
